version: '3.7'
services: 
    openldap:
        image: osixia/openldap:latest
        container_name: openldap
        hostname: openldap
        ports: 
            - "389:389"
            - "636:636"
        volumes: 
            - ./data/certificates:/container/service/slapd/assets/certs
            - ./data/slapd/database:/var/lib/ldap
            - ./data/slapd/config:/etc/ldap/slapd.d
        environment: 
            - LDAP_ORGANISATION=louisgroup
            - LDAP_DOMAIN=louis.local
            - LDAP_ADMIN_USERNAME=admin 
            - LDAP_ADMIN_PASSWORD=140786
            - LDAP_CONFIG_PASSWORD=140786
            - "LDAP_BASE_DN=dc=louis,dc=local"
            - LDAP_TLS_CRT_FILENAME=server.crt
            - LDAP_TLS_KEY_FILENAME=server.key
            - LDAP_TLS_CA_CRT_FILENAME=louis.local.ca.crt
            - LDAP_READONLY_USER=true
            - LDAP_READONLY_USER_USERNAME=greenfield16
            - LDAP_READONLY_USER_PASSWORD=140786
        networks: 
            - openldap

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        container_name: phpldapadmin
        hostname: phpldapadmin
        ports: 
            - "80:80"
        environment: 
            - PHPLDAPADMIN_LDAP_HOSTS=openldap
            - PHPLDAPADMIN_HTTPS=false
        depends_on: 
            - openldap
        networks: 
            - openldap

    networks: 
        openldap:
            driver: bridge